language: node_js
  # cache:
  #     apt: true
  #     directories:
  #         - node_modules # 缓存不经常更改的内容

install: 
  - npm install yarn -g
  - yarn
  - yarn run demo
  - git commit -m "Commit Message" -a

script: true

deploy:
  provider: releases
  api_key: ${GITHUB_TOKEN}
  file_glob: true
  file: "./src/**"
  skip_cleanup: true
  on:
    tags: true
