language: node_js
node_js:
  - "8"
cache:
    apt: true
    directories:
        - node_modules # 缓存不经常更改的内容

install: 
  - npm install

script:
  - npm run demo

deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  github_token: $GITHUB_TOKEN
  local_dir: src
  on:
    branch: master
