language: node_js
node_js:
  - "8"
cache:
    apt: true
    directories:
        - node_modules # 缓存不经常更改的内容

install: 
  - npm install

script:
  - npm run demo

after_script:
  - git add --all
  - git commit -m "Commit Message from travis" -a

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master