language: node_js
node_js:
  - "12"
cache:
    apt: true
    directories:
        - node_modules # 缓存不经常更改的内容

install: 
  - yarn

script:
  - yarn run demo
  - yarn run build-sprites

deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  github_token: $GITHUB_TOKEN
  local_dir: public
  on:
    branch: master
