language: node_js
node_js:
  - "8"
cache:
    apt: true
    directories:
        - node_modules # 缓存不经常更改的内容

install: 
  - npm install

script:
  - npm run demo
  - git add --all
  - git commit -m "Commit Message from travis" -a

deploy:
  provider: releases
  api_key: ${GITHUB_TOKEN}
  skip_cleanup: true
  draft: true
