language: node_js
node_js:
  - "8"

install: 
  - npm install yarn -g
  - yarn
  - yarn run demo

script: 
  - travis setup releases --pro

deploy:
  provider: releases
  api_key: ${GITHUB_TOKEN}
  file: "./src"
  skip_cleanup: true
  on:
    tags: true
