language: node_js
node_js:
  - "8"
cache:
    apt: true
    directories:
        - node_modules # 缓存不经常更改的内容

install: 
  - npm install
  - npm run demo

script: 
  - git add --all
  - git commit -m "Commit Message from travis" -a
  - git push --all

deploy:
  provider: releases
  api_key: ${GITHUB_TOKEN}
  file_glob: true
  file: "./src/**"
  skip_cleanup: true
  on:
    tags: true
