language: node_js
node_js:
  - "8"
cache:
    apt: true
    directories:
        - node_modules # 缓存不经常更改的内容

install: 
  - npm install

script:
  - npm run demo

after_script:
  - git add --all
  - git commit -m "Commit Message from travis" -a

deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  file_glob: true
  file: 
    src/*
    src/** 
  on:
    branch: master