language: node_js
node_js:
  - "8"

install: 
  - npm install yarn -g
  - yarn
  - yarn run demo

script: true

deploy:
  provider: releases
  api_key: "jF7Qh4h3E8vBHYwX7CsEjg"
  file: "FILE TO UPLOAD"
  skip_cleanup: true
  on:
    tags: true
